fog/fog-vsphere

- gemfiles/Gemfile.1.9.2-
- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/models/compute/process.rb
- lib/fog/vsphere/models/compute/server.rb
- lib/fog/vsphere/requests/compute/list_processes.rb
- tests/models/compute/server_tests.rb
Includes
- 14a4e94bbcd7c9d5c207199d076a555d2918be0b
- Use 1.8-style hash syntax for 1.8 compatability
> Add interim commits to fog/fog

- lib/fog/vsphere/requests/compute/create_vm.rb
This ports https://github.com/fog/fog/pull/3754 to fog-vsphere.
@plribeiro3000: As discussed.
> allow setting of boot order when using api > 5.0

- lib/fog/vsphere/requests/compute/list_vm_snapshots.rb
> Fix nil error when snapshots is called on a vm with no snapshots

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/requests/compute/get_storage_pod.rb
- lib/fog/vsphere/requests/compute/list_storage_pods.rb
- tests/requests/compute/list_storage_pods_test.rb
This PR adds some basic mocking and a basic test... Nothing fancy, but a start...
> add mocking and basic test for storage pods

- fog-vsphere.gemspec
- lib/fog/vsphere.rb
- tests/class_from_string_tests.rb
- tests/helper.rb
- Add Minitest
- Write unit tests around complex implementation
- Refactor complex code
- Ensure test still pass
> Refactor unnecessarily complex helper

- lib/fog/vsphere/requests/compute/vm_clone.rb
Just a little refactoring for vm cloning to also check whether storage_pod is nil and not just if the key exists
> refactor storage pod handling

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/models/compute/cluster.rb
- lib/fog/vsphere/models/compute/datastores.rb
- lib/fog/vsphere/models/compute/networks.rb
- lib/fog/vsphere/requests/compute/list_datastores.rb
- lib/fog/vsphere/requests/compute/list_networks.rb
- tests/models/compute/cluster_tests.rb
- tests/requests/compute/list_datastores_tests.rb
- tests/requests/compute/list_networks_tests.rb
This PR adds the ability to view datastores and networks filtered by cluster.
> add cluster storage and network filter

- lib/fog/vsphere/requests/compute/vm_clone.rb
> moved custom_spec['ipsettings'] section inside check for key

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/models/compute/scsicontroller.rb
- lib/fog/vsphere/requests/compute/modify_vm_controller.rb
-- adding the ability to add a scsi controller to a vm.
> adding the add_vm_controller function

- lib/fog/vsphere/models/compute/server.rb
This PR implements updating of cpus, corespersocket and memory for an existing vm.
> support updating of server cpus and memory

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/models/compute/server.rb
- lib/fog/vsphere/models/compute/volume.rb
- lib/fog/vsphere/requests/compute/vm_reconfig_volumes.rb
This PR adds the method vm_reconfig_volumes which updates the size of all attached virtual disks.
> add vm_reconfig_volumes

- lib/fog/vsphere/models/compute/server.rb
This PR extends the save method of server model to update changed volumes.
Related to #67
> update volumes when server save method is called

- lib/fog/vsphere/requests/compute/vm_clone.rb
It was removed in this commit 60a5dc320973ff6425bc941f24bae4e9187b57fa
> remove index argument to create_disk call

- lib/fog/vsphere/models/compute/server.rb
- lib/fog/vsphere/requests/compute/vm_migrate.rb
options were ignored, except priority, so vm wasn't migrated
> send options to vm_migrate request

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/requests/compute/create_vm.rb
- lib/fog/vsphere/requests/compute/current_time.rb
- lib/fog/vsphere/requests/compute/get_datacenter.rb
- lib/fog/vsphere/requests/compute/get_datastore.rb
- lib/fog/vsphere/requests/compute/get_network.rb
- lib/fog/vsphere/requests/compute/get_storage_pod.rb
- lib/fog/vsphere/requests/compute/get_virtual_machine.rb
- lib/fog/vsphere/requests/compute/list_customfields.rb
- lib/fog/vsphere/requests/compute/list_datacenters.rb
- lib/fog/vsphere/requests/compute/list_processes.rb
- lib/fog/vsphere/requests/compute/list_storage_pods.rb
- lib/fog/vsphere/requests/compute/list_templates.rb
- lib/fog/vsphere/requests/compute/list_virtual_machines.rb
- lib/fog/vsphere/requests/compute/upload_iso.rb
- lib/fog/vsphere/requests/compute/vm_clone.rb
- lib/fog/vsphere/requests/compute/vm_config_vnc.rb
- lib/fog/vsphere/requests/compute/vm_execute.rb
- lib/fog/vsphere/requests/compute/vm_migrate.rb
- lib/fog/vsphere/requests/compute/vm_power_off.rb
- lib/fog/vsphere/requests/compute/vm_power_on.rb
- lib/fog/vsphere/requests/compute/vm_reboot.rb
- lib/fog/vsphere/requests/compute/vm_suspend.rb
This is a fix for `RbVmomi::Fault: NotAuthenticated:` when the connection gets stale. The code validates the vsphere connection before use and reconnects if the session expired.
> validate connection before use

- lib/fog/vsphere/requests/compute/list_resource_pools.rb
Hi,
the request list_resource_pools is now able to fetch all subresource pools. 
It would be glad if you integrate the pull request into the main repo.
Thanks!
Best,
theOpenBit
> query subresource pools

- lib/fog/vsphere/requests/compute/vm_clone.rb
When cloning a VM from a template that has the boot order set, the operation may fail with the error `InvalidArgument: A specified parameter was not correct (configSpec.boot Options.boot Order)`. This is because the boot order setting references both storage volumes and network interfaces. During a clone operation (e.g. via Foreman), the network interface of the vm is replaced. The interface from the template is deleted and a new interface is added. The boot order reference is not updated and therefore invalid.
I did not find a way to actually modify the boot order of a vm during cloning, however I found a workaround for this: Instead of deleting the interface from the template and adding a new one, it's possible to update/edit the interface. Therefore the boot order reference doesn't get …
> vm clone: merge nics

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/requests/compute/vm_relocate.rb
I'm not sure how to add this to server model, or how to integrate in reconfig_volumes method of server model
> add vm_relocate request which issues RelocateVM_Task

- lib/fog/vsphere/requests/compute/vm_migrate.rb
Sometimes a vm can't migrate to some hosts, it's possible to check if migration would work with CheckMigrate_Task and get errors and warnings. I added 'check' option to vm_migrate to run CheckMigrate_Task and return erorrs and warnigns
> check option for vm_migrate, using vmProvisioningChecker.CheckMigrate_Task

- lib/fog/vsphere/requests/compute/vm_clone.rb
add disk relocation spec to CloneVM_Task, so volumes from template can be relocated to different datastore
> Support cloning volumes in different datastore

- lib/fog/vsphere/requests/compute/vm_clone.rb
This commit allows a developer to specify a new boot order for the cloned VM similar to when creating a new VM.
> clone_vm: change boot order

- lib/fog/vsphere/requests/compute/vm_clone.rb
interface local variable does not exist, it is template_nic
> fix removing interfaces on vm_clone

- lib/fog/vsphere/requests/compute/vm_clone.rb
PR #114 was wrong:
previous code was using Fog::Compute::Vsphere::Interface
but template_nics are RbVmomi::VirtualDevice now
> Fix commit 28c44d21b3217ce54faaedb789f0009919b6ea42

- lib/fog/vsphere/requests/compute/list_networks.rb
> networks: vlan property not available for DVPortSetting

- lib/fog/vsphere/requests/compute/list_vm_interfaces.rb
- lib/fog/vsphere/requests/compute/modify_vm_interface.rb
> Require a network's datacenter for #update_vm_interface (#139)

- lib/fog/vsphere/requests/compute/list_networks.rb
Fixes #144.
Before:
real	0m17.545s
user	0m2.347s
sys	0m0.653s
After:
real	0m2.852s
user	0m1.068s
sys	0m0.233s
@chris1984: Do you mind testing this in your environment? Thanks.
> speed up network listing

- lib/fog/vsphere/requests/compute/create_vm.rb
This allows connecting VMs to NSX-T Logical Switches. Please merge.
> Add NSX-T support in create_vm.rb

- lib/fog/vsphere/requests/compute/list_vm_interfaces.rb
PR to work to prevent this with a hard fail:
https://bugzilla.redhat.com/show_bug.cgi?id=1612921
> Help prevent hard fail on nil undefined legacy networks.

- lib/fog/vsphere/requests/compute/get_cluster.rb
- lib/fog/vsphere/requests/compute/list_datastores.rb
@chris1984: The same for datastores. This reduces load times from ~50s to ~4s.
From my findings, Folders and Datastores take the longest in Foreman.
> speed up datastore loading

- lib/fog/vsphere/requests/compute/create_vm.rb
- lib/fog/vsphere/requests/compute/get_datastore.rb
- lib/fog/vsphere/requests/compute/get_storage_pod.rb
- lib/fog/vsphere/requests/compute/list_datastores.rb
- lib/fog/vsphere/requests/compute/list_storage_pods.rb
@chris1984: Yet another one, storage pods this time.
> speed up storage pod loading

- lib/fog/vsphere/requests/compute/get_folder.rb
- lib/fog/vsphere/requests/compute/list_folders.rb
This uses the same technique we introduced for networks (a property collector) to load folders more efficiently. In Foreman, this reduced load times of the host create form a lot.
@chris1984: Can you review, test and merge?
> speed up folder loading

- lib/fog/vsphere/requests/compute/get_folder.rb
Enhanced get_folder() and get_raw_folder() implementation to support folder types other than 'vm'
> Support getting folder types other than vm folder

- lib/fog/vsphere/requests/compute/vm_clone.rb
@manchiu do you want to review/test this for me, while I take care of the Foreman tests?
> Fixes #179 - Update vm_clone template to not always be false.

- fog-vsphere.gemspec
- lib/fog/vsphere/requests/compute/get_cluster.rb
- lib/fog/vsphere/requests/compute/get_network.rb
- tests/helper.rb
- tests/requests/compute/get_network_tests.rb
- tests/requests/compute/vm_clone_tests.rb
It would deserve to refactor them more, but I believe, we should switch to minitest as the core did anyway, so I believe now it is about at least passing.
> Tests passing

- lib/fog/vsphere/compute.rb
- lib/fog/vsphere/models/compute/server.rb
Makes the boot_order into an attribute and make it available for read.
> Refs #193 - retrieve boot_order

- lib/fog/vsphere/requests/compute/update_vm.rb
Refactor the method to find out if network update is necessary, to actually work.
> Make network update possible

- lib/fog/vsphere/requests/compute/vm_clone.rb
(cherry picked from commit b053818f8347b41517e73ce81871427b4cb1c937)
> Fixes #201 - added disks on vm cloning (#202)

- lib/fog/vsphere/requests/compute/create_vm.rb
- lib/fog/vsphere/requests/compute/vm_clone.rb
Enables support for the VM to be deployed across multiple storagePods.
> Fixes #212 - enable multiple storage clusters

- lib/fog/vsphere/requests/compute/create_vm.rb
> References #239 - check cluster

- .travis.yml
Address https://github.com/fog/fog-vsphere/issues/258
> Remove code climate

- lib/fog/vsphere/requests/compute/vm_take_snapshot.rb
> Fix omitted snapshot-option

- fog-vsphere.gemspec
rbvmomi2 is a maintained fork of rbvmomi.
I'll admit this is completely untested.
> Switch to rbvmomi2
