fog/fog-vsphere

lib/fog/vsphere/compute.rb

This PR changes the behavior of negotiate_revision to negotiate the most recent revision instead of basically enforcing 4.1 for anything newer.

select the most recent api version instead of 4.1

---

.travis.yml

... as tests are failing and support has been dropped.

remove ruby 1.8 from travis test matrix

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/datacenter.rb
lib/fog/vsphere/models/compute/storage_pod.rb
lib/fog/vsphere/models/compute/storage_pods.rb
lib/fog/vsphere/models/compute/volume.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/get_storage_pod.rb
lib/fog/vsphere/requests/compute/list_storage_pods.rb
lib/fog/vsphere/requests/compute/vm_clone.rb

This PR adds storage pods (datastore clusters) to fog. You can create a new vm or clone an existing one.

implement storage pods

---

fog-vsphere.gemspec

Currently we're requiring fog-core ~1.32 which may break as fog-core < 1.35 still has Vsphere class (see issue #10). Updating to fog-core ~> 1.35 solves it.

Require fog-core 1.35.0

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/cdrom.rb
lib/fog/vsphere/models/compute/cdroms.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/list_vm_cdroms.rb
lib/fog/vsphere/requests/compute/modify_vm_cdrom.rb
lib/fog/vsphere/requests/compute/modify_vm_volume.rb
lib/fog/vsphere/requests/compute/upload_iso.rb
lib/fog/vsphere/requests/compute/vm_reconfig_cdrom.rb
tests/requests/compute/list_vm_cdroms_tests.rb
tests/requests/compute/modify_vm_cdrom_tests.rb
tests/requests/compute/vm_reconfig_cdrom_tests.rb

This PR adds code to manage cdrom drives with fog-vsphere.
I could not get the upload iso function to work, not sure if it's broken in rbvmomi or my test infrastructure. The fog code should be fine, though.

implement cdrom options

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/folder.rb
lib/fog/vsphere/requests/compute/create_folder.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/folder_destroy.rb
lib/fog/vsphere/requests/compute/get_folder.rb
lib/fog/vsphere/requests/compute/list_datacenters.rb
lib/fog/vsphere/requests/compute/list_datastores.rb
lib/fog/vsphere/requests/compute/list_networks.rb
lib/fog/vsphere/requests/compute/list_virtual_machines.rb
lib/fog/vsphere/requests/compute/modify_vm_interface.rb
tests/models/compute/servers_tests.rb
tests/requests/compute/folder_destroy_tests.rb

Sorry this pull request is in two parts - unfortunately one depends on the other (although this can be rectified if required).
1. Adds/expands some more of the mocks (`create_folder`, `get_folder`, `list_datacenters`, `list_datastores`, `list_networks`, and several additions to `list_virtual_machines`). This doesn't break any of the tests except one that was using `servers.get` with a VM ID instead of a name - something that isn't supported by the real `servers.get`. We use these new mocks in our own tests but if you'd like them not to be merged upstream I can pull out the other part of this pull request separately.
2. Adds a `#destroy` to folder models and the associated `folder_destroy` request along with its mocks and a shindo test for it.

Add more mocks and add folder.destroy

---

lib/fog/vsphere/requests/compute/list_vm_interfaces.rb
lib/fog/vsphere/requests/compute/modify_vm_interface.rb

The previous implementation of update_vm_interface attempted to do a `ModifyVM_Task` using a new interface, freshly created with `create_interface()`.
On our environment, this caused the VM to be left with an unusable interface, with properties that I couldn't even examine without getting a 403 back from the server.
This version of update_vm_interface takes the *existing* raw interface object from the API and edits the network backing inside that object before submitting it back as a `ModifyVM_Task`.
This fixes the issue for us. Could you please take a look and decide if it belongs upstream?

Fix update_vm_interface

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/requests/compute/create_vm.rb

This pull request adds the following options to the `create_vm` request:
1. `:annotation`: Allows setting of the notes field on a VM during creation.
2. `:boot_retry`: Set to a number of *ms*, will set the boot option to retry failed boots after that number of *ms*.
3. `:extra_config`: Allows passing of a hash to use as `extra_config` instead of the default one with `bios.bootOrder`.

Additional create_vm options

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/cluster.rb
lib/fog/vsphere/models/compute/rule.rb
lib/fog/vsphere/models/compute/rules.rb
lib/fog/vsphere/requests/compute/create_rule.rb
lib/fog/vsphere/requests/compute/destroy_rule.rb
lib/fog/vsphere/requests/compute/get_cluster.rb
lib/fog/vsphere/requests/compute/list_rules.rb
tests/models/compute/rules_tests.rb

This pull request adds support for DRS (affinity/anti-affinity) rules on a cluster. It adds:
* `cluster.rules`
* `cluster.rules.get`
* `cluster.rules.create` (or `new` &rarr; `vms=` &rarr; `save`)
* `rule.vms`
* `rule.destroy`
It's probably slightly controversial because it moves the `@connection` object into a shadow class to work around a longstanding bug in RbVmomi with respect to passing integers to the `xsd:any` type. (VMware expects an `xsd:int` but for some reason RbVmomi sends an `xsd:long`).
If you absolutely don't want the shadow class, I can take this code out, but I'll have to strip out the whole `destroy` functionality as this currently depends on passing the integer key to an `xsd:any`.
Let me know what you think!

Add support for DRS Rules

---

lib/fog/vsphere.rb

- Remove the require of 'fog/vsphere/compute'
- Add module Compute and autoload Vsphere (previous autoload was reversed)

Fix Fog::Mock.reset properly

---

lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/vm_clone.rb

When querying the vsphere api for resource pools, it returns the pool
"Resources" which basically means "no pool". When creating a vm on that
pool, the creation fails. This commit fixes this behavior by creating
the vm on the cluster object.

Fix cannot create vm on "Resources" resource pool

---

lib/fog/vsphere/models/compute/folder.rb
lib/fog/vsphere/models/compute/servers.rb
lib/fog/vsphere/requests/compute/get_folder.rb
lib/fog/vsphere/requests/compute/get_virtual_machine.rb
lib/fog/vsphere/requests/compute/list_virtual_machines.rb

Prior to this pull request, if you call `#vms` on a folder, the folder information is lost. This means:
* If you do `folder.vms.get(name)` it will actually fetch *every* VM in the datacenter and return a VM by that name wherever it lives, whether it's in the folder or not. This is both (incredibly) slow and leaky.
* If you do `folder.vms.create(hash)` you need to include datacenter and folder information in the hash even though they're already known by `folder`.
This pull request addresses these issues by changing this behaviour:
* `folder.vms.get(name)` will only return the VM if it is in the specified folder itself.
* `folder.vms(recursive: true).get(name)` will return the VM if it is in the specified folder or any of its children.
* `vms.create(hash)` will include …

Pass folder information to more VM operations

---

lib/fog/vsphere/requests/compute/create_vm.rb

I found a small, but very annoying bug in the storage pod code. Here is the fix.

storage pods: fix wrong string assignment

---

lib/fog/vsphere/requests/compute/upload_iso.rb

This PR fixes some issues with upload_iso.
* datastore.upload does not give a proper return code, so we check if the uploaded file actually exists on the datastore
* the create directory command expects a raw datacenter, not a fog datacenter object
* it should create the upload_directory on the datastore

improve upload_iso

---

lib/fog/vsphere/requests/compute/vm_clone.rb

We already support this option in `create_vm`. I've tested
with ESXi 5.1 and works fine.

Expose numCoresPerSocket in vm_clone

---

lib/fog/vsphere/requests/compute/vm_clone.rb

Found myself needing this to [configure CoreOS VMs](https://coreos.com/os/docs/latest/booting-on-vmware.html) automatically.  Let me know if there's anything I should improve with tests / docs / refactoring (the `extra_config` formatting function comes from create_vm.rb).

Allow extraConfig options when cloning VMs.

---

lib/fog/vsphere/requests/compute/create_folder.rb
lib/fog/vsphere/requests/compute/create_vm.rb

Currently, if anything gets caught by either of these handlers then the re-raised exception will be lacking the original stacktrace, which makes debugging the underlying cause impossible.
Example trace;
```
failed to create vm: NoPermission: Permission to perform this operation was denied.
RbVmomi::Fault: failed to create vm: NoPermission: Permission to perform this operation was denied.
/usr/lib/ruby/gems/2.1.0/gems/fog-vsphere-1.0.0/lib/fog/vsphere/requests/compute/create_vm.rb:44:in `rescue in create_vm'
/usr/lib/ruby/gems/2.1.0/gems/fog-vsphere-1.0.0/lib/fog/vsphere/requests/compute/create_vm.rb:8:in `create_vm'
/usr/lib/ruby/gems/2.1.0/gems/fog-vsphere-1.0.0/lib/fog/vsphere/models/compute/server.rb:273:in `save'
/usr/share/foreman/app/models/compute_resources/foreman/model/vmware.rb:3 …
```

Don't destroy stacktrace when things go wrong

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/requests/compute/create_group.rb
lib/fog/vsphere/requests/compute/destroy_group.rb
lib/fog/vsphere/requests/compute/get_host.rb
lib/fog/vsphere/requests/compute/list_groups.rb

In this pull request I'm adding new functionality that will be providing fog-vsphere with the ability to create, list and destroy DRS groups.  The first commit contains the changes and in the second commit I merely pulled the upstream master and merged to check for any merge conflicts.

Adding new functionality for creating, listing and destroying DRS groups

---

lib/fog/vsphere/requests/compute/vm_clone.rb

When there is no `nicSettingMap` key in `custom_spec`, it results in:
```
| NoMethodError: undefined method `length' for nil:NilClass
| /home/vagrant/.rvm/gems/ruby-2.2.4/gems/fog-vsphere-1.2.0/lib/fog/vsphere/requests/compute/vm_clone.rb:520:in `vm_clone'
```
because `custom_nicSettingMap` is nil

Do not fail on 'undefined method' when nicSettingMap not present

---

fog-vsphere.gemspec

Puppet gem "beaker" currently can't install due to two conflicting version dependencies on the rbvmomi package. The most logical fix is to upgrade the dependency on this gem to the stable series 1.9.x , rather than downgrading Beaker's dependency version.
```
Bundler could not find compatible versions for gem "rbvmomi":
In Gemfile:
beaker (>= 0) ruby depends on
rbvmomi (~> 1.9) ruby
beaker (>= 0) ruby depends on
fog (~> 1.38) ruby depends on
fog-vsphere (>= 0.4.0) ruby depends on
rbvmomi (~> 1.8.0) ruby
```
This PR increments the dependency and passes all unit tests. If happy, please upload to RubyGems ASAP since it'll break beaker in weird ways ATM, which will cause headaches for anyone unit testing Puppet modules.
It may be worth reconsidering how the dependencies are being managed for …

Upgrade rbvmomi depenency to latest stable series (1.9.x)

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/models/compute/volume.rb
lib/fog/vsphere/models/compute/volumes.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/list_vm_scsi_controllers.rb
lib/fog/vsphere/requests/compute/list_vm_volumes.rb

This commit adds the ability to add more than one scsi controller to a vm.
This can be tested with:
```ruby
attrs = {
...
:volumes => [
{
:storage_pod=>"Test",
:name=>"Hard disk 1",
:size_gb=>"10",
:thin=>"true",
:eager_zero=>"false",
:controller_key => 1000
},
{
:storage_pod=>"Test",
:name=>"Hard disk 2",
:size_gb=>"10",
:thin=>"true",
:eager_zero=>"false",
:controller_key => 1001
}
],
:scsi_controllers => [
{
:type=>"VirtualLsiLogicController",
:key => 1000
},
{
:type=>"VirtualLsiLogicController",
:key => 1001
}
]
}
vm = client.servers.new(attrs)
vm.save
```

vms can have more than one scsi controller

---

lib/fog/vsphere/models/compute/scsicontroller.rb
lib/fog/vsphere/models/compute/volume.rb

fog-core sets these attributes "too late" and this can cause issues.

set default values more reliable

---

lib/fog/vsphere/models/compute/volume.rb
lib/fog/vsphere/requests/compute/create_vm.rb

Generating the keys ourselves instead of relying on vsphere to do this solves errors when generating the boot order list.

generate volume key reliably

---

lib/fog/vsphere/requests/compute/get_virtual_machine.rb

Since we fetch the list of all VMs first and then iterate over them we might
crash since VSphere refuses to report properly on VMs that are being created or
removed and we're doing API calls for each VM until we found a matching one:
/home/test-vspehere/vendor/ruby/2.1.0/gems/rbvmomi-1.9.4/lib/rbvmomi/connection.rb:61:in `parse_response': ManagedObjectNotFound: Das Objekt wurde bereits gel??scht oder noch nicht vollst??ndig erstellt (RbVmomi::Fault)
from /home/test-vspehere/vendor/ruby/2.1.0/gems/rbvmomi-1.9.4/lib/rbvmomi/connection.rb:90:in `call'
from /home/test-vspehere/vendor/ruby/2.1.0/gems/rbvmomi-1.9.4/lib/rbvmomi/basic_types.rb:211:in `_call'
from /home/test-vspehere/vendor/ruby/2.1.0/gems/rbvmomi-1.9.4/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
from …

get_vm_folder_name: Don't crash when VMs disappear

---

lib/fog/vsphere/requests/compute/vm_clone.rb

there is no attributes variable in vm_clone, cluster_name should be used

fix vm clone with resource pool

---

lib/fog/vsphere/requests/compute/modify_vm_interface.rb

It allows to change :connected prop for interface, or
startConnected prop.
Using with server.update_interface should work:
server.update_interface interface: interface, connectable: {connected: true, startConnected: true}
Fixes #81

Add :connectable options to update_vm_interface

---

lib/fog/vsphere/models/compute/volume.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/modify_vm_volume.rb
lib/fog/vsphere/requests/compute/vm_reconfig_volumes.rb

- Add detach to volume model
- Add remove_vm_volume as a request, it remove volume from vm without deleting file
- Refactored create_disk so it can be used for remove volume without deleting file, and reuse it in vm_reconfig_volumes request

Add ability to detach volume from VM

---

lib/fog/vsphere/requests/compute/list_clusters.rb

This causes problems when DC name contains characters that have extra meaning in regular expressions e.g. parenthesis. The prefix is not matched and the full name contains also DC name. Later when we search for such cluster, it can't be found.

Properly escape DC names

---

lib/fog/vsphere/models/compute/snapshots.rb

it was returning root snapshot with requested descendent, instead of requested snapshot

fix snapshots.get for non-root snapshot

---

lib/fog/vsphere/models/compute/snapshots.rb

My previous commit fixed snapshots.get for existing id, but broke it for unexisting id, it was returning snapshots array instead of nil

fix snapshots.get(id) when no snapshot is found

---

lib/fog/vsphere/requests/compute/list_networks.rb

Resolves #92 by checking the network type and using the key attribute as ID if type is 'DistributedVirtualPortgroup'.

use portgroupkey to identify dv portgroup networks

---

lib/fog/vsphere/requests/compute/vm_clone.rb

Resolves #69 by calling the target cluster resource pool, instead of the template's host's resource pool, when using the default resource pool.

Do not fail when cloning from template to different cluster

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/models/compute/ticket.rb
lib/fog/vsphere/models/compute/tickets.rb
lib/fog/vsphere/requests/compute/vm_acquire_ticket.rb
tests/models/compute/server_tests.rb
tests/models/compute/ticket_tests.rb
tests/models/compute/tickets_tests.rb

This patch allows to acquire a webmks ticket for a server. This can be used with https://www.vmware.com/support/developer/html-console/.

server can acquire webmks ticket

---

lib/fog/vsphere/models/compute/server.rb

Total n00b here to Git.  Done quite a bit of Ruby coding, so if I've done something incorrect as far as preferred Git process goes, please correct my behavior and I'll correct it the next time!
I found via Foreman that trying to power off an already powered off system, resulted in a 500 internal server error.  This is simple validation to not run the start/stop operations via RbVmomi if they are already in their desired state.

Fixed validation for power on/off requests (foreman)

---

.gitignore
lib/fog/vsphere/requests/compute/list_clusters.rb
tests/class_from_string_tests.rb

This shouldn't be a breaking change, old behavior is retained while allowing you to not pass a datacenter parameter. It also ensures that only `RbVmomi::VIM::ClusterComputeResources` are returned as clusters. No more pesky standalone hosts!

Updated list_clusters to have an optional param or allow filtering on datacenter

---

lib/fog/vsphere/requests/compute/vm_clone.rb

https://github.com/fog/fog-vsphere/pull/98 introduced a regression that leads to duplicate mac addressed because the cloned host keeps the mac addresses of the parent host.
This forces the generation of new mac addresses during cloning.

vm clone: generate new mac addresses

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/cluster.rb

It currently isn't possible to list cluster's resources when the cluster is nested in a folder. This PR fixes it by using `full_path` (eg. `"nested/folder/cluster"`) instead of `name` (eg. just `"cluster"`) as a cluster identifier in the resource queries.

Fixes listing resource pools for clusters nested in folders

---

lib/fog/vsphere/requests/compute/list_clusters.rb

We have the following setup:
Datacenter: XYZ
Folder: ABC - XYZ
Cluster: Whatever
The regex tries to remove the datacenter name XYZ, but also remove part of the path which breaks the lookup of the resource pools later on.
By adding the ^ before the DC name in the regex, we ensure only that part is removed.

Fix regex issue when folder contains the datacenter name

---

.travis.yml
fog-vsphere.gemspec
gemfiles/Gemfile.1.9.2+

Users requiring Ruby 1.9 support should use the fog gem.

Drop Ruby<2 support

---

lib/fog/vsphere/requests/compute/list_hosts.rb

rescue nil for retrieving vm.config.instanceUuid if somehow the VM is not able to be retrieved (nil class for VM)

rescue nil for retrieving vm.config.instanceUuid (fixes #123)

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/requests/compute/get_datastore.rb
lib/fog/vsphere/requests/compute/get_network.rb
lib/fog/vsphere/requests/compute/get_storage_pod.rb
lib/fog/vsphere/requests/compute/list_storage_pods.rb
lib/fog/vsphere/requests/compute/list_templates.rb
lib/fog/vsphere/requests/compute/list_virtual_machines.rb

fog-vsphere uses Views to get data from vSphere. These views need to be closed manually or they will pile up and waste resources on the vCenter. This can cause problems when there are no more free resources for other services (eg. NSX Manager) that require them.

ensure views are destroyed after use

---

lib/fog/vsphere/models/compute/network.rb
lib/fog/vsphere/requests/compute/list_networks.rb

This PR adds a new property `vlanId` to the network model. In addition, it also speeds up network listing a lot by not calling `get_raw_network` on a raw network.
@chris1984: Do you mind taking a look?
This can be tested like this:
```
require 'fog'
client = ::Fog::Compute.new(
:provider => 'vsphere',
:vsphere_username => 'ccc',
:vsphere_password => 'ccc',
:vsphere_server => 'ccc',
:vsphere_expected_pubkey_hash => 'ccc'
)
datacenter_name = 'World'
dc = client.datacenters.get(datacenter_name)
dc.clusters.first.networks.all
```
This can be optimized further, but let's keep this simple for now.

networks have vlanId property

---

lib/fog/vsphere/requests/compute/vm_clone.rb

This fixes
```
NoMethodError: undefined method `networkFolder' for nil:NilClass
fog-vsphere/lib/fog/vsphere/compute.rb:674:in `public_send'
fog-vsphere/lib/fog/vsphere/compute.rb:674:in `list_container_view'
fog-vsphere/lib/fog/vsphere/requests/compute/get_network.rb:24:in `get_all_raw_networks'
fog-vsphere/lib/fog/vsphere/requests/compute/get_network.rb:15:in `get_raw_network'
fog-vsphere/lib/fog/vsphere/requests/compute/create_vm.rb:167:in `create_nic_backing'
fog-vsphere/lib/fog/vsphere/requests/compute/vm_clone.rb:754:in `block in modify_template_nics_specs'
fog-vsphere/lib/fog/vsphere/requests/compute/vm_clone.rb:752:in `each'
fog-vsphere/lib/fog/vsphere/requests/compute/vm_clone.rb:752:in `modify_template_nics_specs'
fog-vsphere/lib/fog/vsphere/requests/compute/vm_clone.rb:158:in …
```

vm_clone: pass datacenter to nic backing

---

lib/fog/vsphere/models/compute/host.rb
lib/fog/vsphere/requests/compute/list_hosts.rb

This improves host listing via a property collector. This can be optimized even further, but it's a start. :-)
This can be tested with something like this:
```ruby
require 'fog'
client = ::Fog::Compute.new(
:provider => 'vsphere',
:vsphere_username => 'ccc',
:vsphere_password => 'ccc',
:vsphere_server => 'ccc',
:vsphere_expected_pubkey_hash => 'ccc'
)
datacenter_name = 'World'
dc = client.datacenters.get(datacenter_name)
dc.clusters.first.hosts.all
```
We can use this code as a basis to retrieve other attributes faster.

improve host listing performance

---

lib/fog/vsphere/requests/compute/vm_clone.rb

Fixes #132.
This commit checks if the new_volume has a datastore attribute before trying to relocate it.
The error in the issue happens, because this is passed to vSphere (because `new_volume.datastore` is `nil`):
```
relocation_spec[:disk] -> [{:diskId=>nil, :datastore=>nil}]
```

fix clone vm without datastore relocation

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/requests/compute/get_network.rb
lib/fog/vsphere/requests/compute/update_vm.rb
tests/requests/compute/get_network_tests.rb
tests/requests/compute/update_vm_tests.rb

As part of https://github.com/theforeman/foreman/pull/5569
This adds the functionality to edit the network of an existing network and fixes some other issues with updating a vm. 
It also brings updating a vm into one request to the vsphere sdk reducing it from individual requests for each attribute.

Add vm_update class for improved vm reconfiguration

---

lib/fog/vsphere/models/compute/volume.rb

Don't increment unit_number if 7 or higher, volume won't be found, set_unit_number already avoids setting unit_number to 7.

fix adding 8th volume to vm (fixes #146)

---

lib/fog/vsphere/models/compute/interface.rb
lib/fog/vsphere/models/compute/interfaces.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/requests/compute/modify_vm_interface.rb

Calling server.interfaces.get('mac_address') failed because datacenter is required
It could fail calling server.update_vm_interface because datacenter is required,
or calling interface.destroy

add required datacenter param to all calls which may use get_vm_interface

---

lib/fog/vsphere/models/compute/interface.rb
lib/fog/vsphere/requests/compute/get_datacenter.rb

This patch is for working around create VM interface failure due to datacenter undefined. (undefined method `networkFolder' for nil:NilClass)

patch attribute[:datacenter] for create interface

---

lib/fog/vsphere/requests/compute/cloudinit_to_customspec.rb

This is a pull request for the issue from #93 (Also see theforeman/foreman#6243)
Further information from https://projects.theforeman.org/issues/25457
Two simple line changes allow for the extraConfig from userdata to be passed through to fog-vsphere vm_clone.
This adds the option to pass through guestinfo network configuration for CoreOS VMs.
With the use of Omaha or similar tools even building the ignition configuration and passing it to the VM on clone is an option.
Without this change an additional tool has to be used to supply the guestinfo before the machine is started for the first time.

Expose extraConfig from user_data for vm_clone

---

.travis.yml
lib/fog/vsphere/requests/compute/get_folder.rb

@timogoebel can I get a review please? I tried to make a vm yesterday with with your gist and hit this, looking at the ruby docs .blank is not a method for a string anymore. After switching to .empty I was able to build with the script.

Fixes #188 - Update ruby string method to prevent traceback

---

lib/fog/vsphere/requests/compute/vm_clone.rb

If more disks are specified and their placement is on storagePod, cloning fails.
This is a partial fix though, because now if storagePod is specified, it places all the disks on that pod, no matter what the disks have specified.
It will clone the machine successfuly though.

Fixes #201 - added disks on vm cloning

---

lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/get_network.rb
lib/fog/vsphere/requests/compute/list_networks.rb
tests/requests/compute/get_network_tests.rb

Make the lookup by ref available, what will effectively mean, that this is going to be valid:
```ruby
network_id = compute.networks.first.id # find my desired network
compute.servers.new interfaces: [{network: network_id}]
server = compute.servers.first
server.interfaces.first.network = network_id
```
And it is really convenient to work with id.

Fixes #203 - network lookup by its ref

---

lib/fog/vsphere/requests/compute/update_vm.rb

send cpuHotAddEnabled and memoryHotAddEnabled to ReconfigVM_Task spec, so it can be changed in server model

Save cpu and memory HotAdd enabled from server model

---

lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/vm_clone.rb

Fixes #216 and allows specifying the thin provisioning for cloned VMs from templates.
The main change is in the new disks being added in separate task after the machine is cloned.
The drawback is, that now it is not an atomic action, so if adding the disk fails for some reason, the machine stays in the vcenter.

Fixes #216 - cloning disks thin relocation and storagePod location

---

lib/fog/vsphere/compute.rb

Simple clusters are `RbVmomi::VIM::ComputeResource` not `RbVmomi::VIM::ClusterComputeResource`

Fixes #237 - load simple clusters

---

lib/fog/vsphere/requests/compute/upload_iso.rb

See https://community.theforeman.org/t/vmware-bootdisk-provisioning-will-fail-with-failed-to-upload-iso-image-for-instance/16938/4.

iso upload: correctly check if upload directory exists

---

lib/fog/vsphere/requests/compute/create_vm.rb

Fail with a proper error, when we pass misspelled/bad cluster name to VM creation.

Fixes #239 - check cluster existance

---

lib/fog/vsphere/requests/compute/list_vm_interfaces.rb

@timogoebel with this small fix the nsx-t network selection works again on the lastest commit on master of fog-vsphere making the earlier nsx-t patches active on the latest codebase
@ezr-ondrej if all is approved, I would appreciate a new package release and also a backport to the rpm repo of 1.24 if possible :)
thx all

fixes earlier nsx-t patches

---

lib/fog/vsphere/requests/compute/list_resource_pools.rb

When some resource pool('ParentResourcePool') has nested resource pool('Resources') we get this child resource pool with name 'Resources' without path of parent resource pool('Resources' instead of 'ParentResourcePool/Resources').

list_resource_pools returns incorrect resource pool name #256

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/requests/compute/create_resource_pool.rb
lib/fog/vsphere/requests/compute/destroy_resource_pool.rb
lib/fog/vsphere/requests/compute/update_resource_pool.rb

- I've added posibility manage resource pools(create/update/delete).
- I've faced with some problems with tests that is why I don't add any one :disappointed: but I promise to add when figure out these problems.
Create
```
compute.create_resource_pool(
datacenter: 'datacenter_name', 
cluster: 'cluster_name', 
name: 'resource_pool_name', 
cpu: {reservation: '2000'},
memory: {reservation: '512'}
)
```
Update
```
compute.update_resource_pool(
datacenter: 'datacenter_name', 
cluster: 'cluster_name', 
name: 'new_resource_pool_name', 
cpu: {reservation: '3000'},
memory: {reservation: '1024'},
ref: 'resource_pool_id'
)
```
Delete
```
compute.destroy_resource_pool(
datacenter: 'datacenter_name', 
cluster: 'cluster_name', 
ref: 'resource_pool_id'
)
```

Add ability to create update and delete Resource Pools #253

---

lib/fog/vsphere/requests/compute/create_resource_pool.rb
lib/fog/vsphere/requests/compute/update_resource_pool.rb

Now we can create resource pool with '/' in resource pool and root resource pool namespace.

Fix resource pool creation with '/' in name #261

---

lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/requests/compute/vm_clone.rb

if datacenter option is in clone arguments, add vm's datacenter as template_datacenter, as vm to use as template may be in different datacenter

clone vm in different datacenter

---

lib/fog/vsphere/models/compute/clusters.rb
lib/fog/vsphere/models/compute/customfields.rb
lib/fog/vsphere/models/compute/customvalues.rb
lib/fog/vsphere/models/compute/datacenters.rb
lib/fog/vsphere/models/compute/datastores.rb
lib/fog/vsphere/models/compute/folders.rb
lib/fog/vsphere/models/compute/interfaces.rb
lib/fog/vsphere/models/compute/interfacetypes.rb
lib/fog/vsphere/models/compute/networks.rb
lib/fog/vsphere/models/compute/resource_pools.rb
lib/fog/vsphere/models/compute/rules.rb
lib/fog/vsphere/models/compute/servers.rb
lib/fog/vsphere/models/compute/servertypes.rb
lib/fog/vsphere/models/compute/templates.rb
lib/fog/vsphere/models/compute/tickets.rb
lib/fog/vsphere/models/compute/volumes.rb

autoload is wrongly namespaced for all the models, I think it confuses Rails and causes weird issues.
Issue is described here: https://community.theforeman.org/t/foreman-1-20-2-vmware-sporadic-http-500-when-querying-api-compute-resources-api/13907
@timogoebel don't you know why those `autoload`s are really there? All models are force required in the service class, so wrongly namespaced autoload is probably not what we need, right?

Remove autoload

---

lib/fog/vsphere/models/compute/network.rb

The get_network function in lib/fog/vsphere/requests/compute/get_network.rb
takes a name or _ref attribute.  This commit expose that _reg attribute
(already retrieved via previous vsphere call) so that clients of
fog-vsphere can look up network objects via the globally unique _ref
attribute instead of the non-unique Name attribute.
Additionally, this enables fixing a bug in clients where the id attribute
is incorrectly substituted for _ref, retrieving an incorrect object in
certain VSphere environments.

Expose _ref from Compute::Network #265

---

lib/fog/vsphere/requests/compute/get_network.rb
lib/fog/vsphere/requests/compute/list_networks.rb

Use `_ref` as ID for all kinds of networks.
See https://community.theforeman.org/t/could-not-match-network-interface-vmware-again/20862 for the detailed problem description.

Unify network ID attribute

---

lib/fog/vsphere/requests/compute/get_network.rb
lib/fog/vsphere/requests/compute/list_networks.rb

RHEL 7 - Pass
RHEL 8 - Pass
RHEL 9 - Pass
RHEL 7 - Pass
RHEL 8 - Pass
RHEL 9 - Pass

Revert "Unify network ID attribute"

---

lib/fog/vsphere/requests/compute/vm_clone.rb

Fix for issue #290 which we discovered during dualstack deployments with Redhat Satellite/Foreman

Custom IPv6 specification should be an array - fixes #290

---

lib/fog/vsphere/requests/compute/create_vm.rb

This is a proposed solution for [#2186114](https://bugzilla.redhat.com/show_bug.cgi?id=2186114)
I think creating a host without mentioning the storage pod or the datastore should not be permitted. Adding validation is one way to go but achieving that is extremely difficult. Adding an exception is a much simpler approach to it.
I'm open for any other ideas to approach this problem. Please feel free to share your thoughts on this.
cc: @shimshtein

Add an exception for the missing storage field

---

tests/fixtures/vcr_cassettes/6_7/get_vm_first_sata_controller.yml

952fec59329d15587b0610352233d1caac246369
https://github.com/fog/fog-vsphere/pull/292
Between vmware 8 and 7 these properties changed
```
ha-property-collector vs. propertyCollector
ha-searchindex vs. SearchIndex
```
This should fix the tests that is still failing int this PR https://github.com/fog/fog-vsphere/actions/runs/8919524130/job/24495876299?pr=297

Possible fix for Fixes 'vmware 8 u2 iso detach'

---

fog-vsphere.gemspec

With the catch all approach there were a lot of files included that do not need to be in the gem. I.e. Jenkinsfile, all dot files and dirs related to CI configuration, and rubocop linting ...
This causes problems when i.e. building rpm packages where all of these files need to be explicitly excluded: see https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec#L50

Explicitly list files and dirs included in gemspec (test_)files

---

lib/fog/vsphere/compute.rb
lib/fog/vsphere/models/compute/nvmecontroller.rb
lib/fog/vsphere/models/compute/server.rb
lib/fog/vsphere/models/compute/volume.rb
lib/fog/vsphere/requests/compute/create_vm.rb
lib/fog/vsphere/requests/compute/get_vm_first_nvme_controller.rb
lib/fog/vsphere/requests/compute/list_vm_nvme_controllers.rb
lib/fog/vsphere/requests/compute/vm_clone.rb
tests/fixtures/vcr_cassettes/6_7/get_vm_first_nvme_controller.yml
tests/requests/compute/get_vm_first_nvme_controller_tests.rb

This is the solution for the [feature](https://bugzilla.redhat.com/show_bug.cgi?id=2156673) request. 
NVME (Non Volatile Memory Express) controllers are a class above the currently supported (SCSI Controllers) and has multiple [advantages](https://www.techtarget.com/searchstorage/definition/NVMe-non-volatile-memory-express)
Currently Foreman and fog-vsphere are designed to only support SCSI controllers and it's types. The goal is to extend it to adding NVME and in future, other types. Do give this a read [SCSI, SATA, and NVMe Storage Controller Conditions, Limitations, and Compatibility](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-5872D173-A076-42FE-8D0B-9DB0EB0E7362.html) 
Front End PR : https://github.com/theforeman/foreman/pull/10168
Hammer doc PR …

Add support for NVME Controllers

---

lib/fog/vsphere/compute.rb

This uses the more efficient /regex/.match?(value) syntax that also doesn't raise any warning if id is nil.

Fix warning on nil comparison
